### ISSUE TITLE
Send translation packages

### ISSUE THREAD

**Issue by KentHall2018** [IBM-Bluemix-Docs/bare-metal#10]
@jmilst 
Translation packages need to be sent for the Bare Metal Server repo. There are currently some links that are broken because updated files haven't been sent into translation. 
https://ibm.ent.box.com/file/164493386852 this says that GSA ID=jmilst (jmilst@us.ibm.com), GSA ID = bperish (bpersich@us.ibm.com) is the current owner. 

Here's the TCT issue that has the broken links: https://www-06.ibm.com/software/globalization/translationcommunications/BaseServlet.wss?taskName=ReadArticlePre&arrefnum=7702048067&prrefnum=2000007910. 

The link that is currently broken is for https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-about-bm#about-bm. This link works for English, but it doesn't work the other languages because it hasn't been sent to translation since the topic ID has been changed.

**Comment by jmilst** [comment]
sent to translation - returned and published
