### ISSUE TITLE
Tagging information visible on doc page

### ISSUE THREAD

**Issue by butler54** [IBM-Bluemix-Docs/bare-metal#12]
On here:
https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-bm-hardware-monitroing-security-controls

Some metadata tagging is visible (see attached image)

<img width="1063" alt="Screen Shot 2019-07-03 at 5 06 42 pm" src="https://user-images.githubusercontent.com/19358775/60625259-3b3cea00-9db5-11e9-86b3-6871130852cf.png">

**Comment by jmilst** [comment]
corrected short desc tag
