### ISSUE TITLE
Publish in docs, not Service Now: How do you use LSI commands?

### ISSUE THREAD

**Issue by bwentwor** [IBM-Bluemix-Docs/bare-metal#8]
Back in June, Louis Shin (louisshi@au1.ibm.com) submitted a document to the Service Now knowledge base for publishing entitled, "How do you use LSI commands?" Based on the extensive content in the document, I believe that the information belongs in the IBM Cloud docs and not in the Service Now knowledge base. Please work with Louis to incorporate this content. Here is the information:

[LSI.pdf](https://github.com/IBM-Bluemix-Docs/bare-metal/files/2372284/LSI.pdf)

**Comment by bpersich** [comment]
@bwentwor. Sorry for not updating this issue from previous research.

We've received several requests to move ServiceNow content into IBM Cloud documentation. Most of these requests are to add 3rd party information to our docs. In this case, these are StorCLI commands and are not owned by IBM. It is useful content, but for us to include 3rd party content in the IBM doc requires us also to maintain the information.

For example, if the 3rd party owner changes how a product functions, then our content would be out of date and we don't have a way of being notified of that.

**Comment by bpersich** [comment]
Closing.
